{"name": "test_mul_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_file3.Test_Credence_003 object at 0x000001657A9977D0>\n\n    def test_mul_004(self):\n        a = 3\n        b = 7\n        mul = a * b\n        print(\"Mul of a and b is :\" + str(mul))\n        if mul == 10:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntest_file3.py:11: AssertionError"}, "start": 1690715212145, "stop": 1690715212145, "uuid": "f7c92769-a24e-49af-9627-9cff6f3c10a9", "historyId": "b5a535ee3b4f399417f06f2bf4d09172", "testCaseId": "b5a535ee3b4f399417f06f2bf4d09172", "fullName": "test_file3.Test_Credence_003#test_mul_004", "labels": [{"name": "suite", "value": "test_file3"}, {"name": "subSuite", "value": "Test_Credence_003"}, {"name": "host", "value": "SUMI-LAPTOP"}, {"name": "thread", "value": "2144-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_file3"}]}